/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-06-04 10:55:30 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=EUC-KR\">\n");
      out.write("<title>회원가입</title>\n");
      out.write("<style>\n");
      out.write("\tdiv.title{\n");
      out.write("\t\twidth: 1000px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\tmargin-left: -450px;\n");
      out.write("\t\tmargin-top: 100px;\n");
      out.write("\t\tfont: bold 15px, sans-serif;\n");
      out.write("\t}\n");
      out.write("\tdiv.join{\n");
      out.write("\t\twidth: 1000px;\n");
      out.write("\t\tmargin-left: -500px;\n");
      out.write("\t\tpadding: 50px 100px;\n");
      out.write("\t}\n");
      out.write("\ttable{\n");
      out.write("\t\twidth: 900px;\n");
      out.write("\t\tborder: 3px solid black;\n");
      out.write("\t\tborder-collapse: collapse;\n");
      out.write("\t}\n");
      out.write("\ttd{\n");
      out.write("\t\tborder: 1px solid black;\t\n");
      out.write("\t}\n");
      out.write("\ttfoot{\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\ttd.tag{\n");
      out.write("\t\theight: 35px;\n");
      out.write("\t\twidth: 150px;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t}\n");
      out.write("\ttd.t{\n");
      out.write("\t\tpadding: 10px 20px;\n");
      out.write("\t}\n");
      out.write("\ttd.t_pic{\n");
      out.write("\t\tpadding: 50px 0px 50px 100px;\n");
      out.write("\t}\n");
      out.write("\ttd img{\n");
      out.write("\t\tpadding: 10px;\n");
      out.write("\t}\n");
      out.write("\tp.pinfo{\n");
      out.write("\t\tpadding-left: 20px;\n");
      out.write("\t\twidth: 900px;\n");
      out.write("\t\theight: 150px;\n");
      out.write("\t\toverflow: auto;\n");
      out.write("\t}\n");
      out.write("\ttd.ag1{\n");
      out.write("\t\tpadding: 20px;\n");
      out.write("\t\theight: 50px;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div style=\"width: 0px; margin:auto;\">\n");
      out.write("\t<div class=\"title\"><h2>Join Member</h2></div>\n");
      out.write("\t<div class=join>\n");
      out.write("\t<form action=signUp method=\"post\">\n");
      out.write("\t\t<table>\n");
      out.write("\t\t\t<caption>기본 정보</caption>\n");
      out.write("\t\t\t<tbody>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">아이디</td><td class=\"t\"><input type=text name=\"id\" maxlength=16>&nbsp;&nbsp;(최대 16자)</td></tr>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">비밀번호</td><td class=\"t\"><input type=password name=\"password\" maxlength=16>&nbsp;&nbsp;(최대 16자)</td></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"tag\">학과</td>\n");
      out.write("\t\t\t\t\t<td class=\"t\">\n");
      out.write("\t\t\t\t\t\t<select name=\"major\" size=\"1\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"경영학부\">경영학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"국제학부\">국제학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"동아시아언어문화학부\">동아시아언어문화학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"미디어기술콘텐츠학과\">미디어기술콘텐츠학과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"법정경학부\">법정경학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"사회과학부\">사회과학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"생명환경학부\">생명환경학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"생활과학부\">생활과학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"영어영문학부\">영어영문학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"음악과\">음악과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"인문학부\">인문학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"자연과학부\">자연과학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"정보통신전자공학부\">정보통신전자공학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"종교학과\">종교학과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"컴퓨터정보공학부\">컴퓨터정보공학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"특스교육과\">특수교육과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"프랑스어문화학과\">프랑스어문화학과</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">나이</td><td class=\"t\"><input type=text name=\"age\" maxlength=2>&nbsp;살</td></tr>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">핸드폰 번호</td><td class=\"t\"><input type=text name=\"phone\" maxlength=13 placeholder=\"010-xxxx-xxxx-\">&nbsp;('-'를 포함하여 입력해주세요)</td></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"tag\">프로필 사진</td>\n");
      out.write("\t\t\t\t\t<td class=\"t_pic\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man1.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man1\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man2.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man2\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man3.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man3\"><br>\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man4.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man4\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man5.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man5\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man6.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man6\"><br>\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man7.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man7\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man8.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man8\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man9.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man9\"><br>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<input type=\"submit\" value=\"회원가입\">\t\n");
      out.write("\t\t</form>\t\t\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
