/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.17
 * Generated at: 2019-06-10 01:53:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class SignUp_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=EUC-KR");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<link href=\"css/signup.css\" type=\"text/css\" rel=\"stylesheet\">\n");
      out.write("<meta charset=\"EUC-KR\">\n");
      out.write("<title>SingUpForm</title>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tfunction regi(){\n");
      out.write("\t\tif(document.join.id.value==''){\n");
      out.write("\t\t\talert(\"아이디를 입력하세요\");\n");
      out.write("\t\t\tdocument.join.id.focus();\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(document.join.password.value==''){\n");
      out.write("\t\t\talert(\"비밀번호를 입력하세요\");\n");
      out.write("\t\t\tdocument.join.password.focus();\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(document.join.major.value==''){\n");
      out.write("\t\t\talert(\"전공을 입력하세요\");\n");
      out.write("\t\t\tdocument.join.major.focus();\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(document.join.age.value==''){\n");
      out.write("\t\t\talert(\"나이를 입력하세요\");\n");
      out.write("\t\t\tdocument.join.age.focus();\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(document.join.phone.value==''){\n");
      out.write("\t\t\talert(\"핸드폰 번호를 입력하세요\");\n");
      out.write("\t\t\tdocument.join.phone.focus();\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(document.join.pr.value==''){\n");
      out.write("\t\t\talert(\"자기소개를 입력하세요\");\n");
      out.write("\t\t\tdocument.join.pr.focus();\n");
      out.write("\t\t}\n");
      out.write("\t\telse if(!(join.photo[0].checked||join.photo[2].checked||join.photo[3].checked\n");
      out.write("\t\t\t\t||join.photo[4].checked||join.photo[5].checked||join.photo[6].checked\n");
      out.write("\t\t\t\t||join.photo[7].checked||join.photo[8].checked||join.photo[1].checked)){\n");
      out.write("\t\t\talert(\"사진을 선택하세요\");\n");
      out.write("\t\t}\t\t\n");
      out.write("\t\telse{\n");
      out.write("\t\t\tdocument.join.submit();\n");
      out.write("\t\t\treturn true;\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("</script>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<section>\n");
      out.write("\t\t<div class=\"logo\">\n");
      out.write("  \t\t\t<span>CUKBM</span><br> \t\n");
      out.write("  \t\t</div>\t\t\n");
      out.write("\t</section>\n");
      out.write("<header>\n");
      out.write("  <nav>\n");
      out.write("    <a href=\"CUKBM_FrontPage.jsp\">HOME</a>\n");
      out.write("\t<a href=\"Login.jsp\">LOGIN</a>\n");
      out.write("\t<a href=\"Agreement.jsp\">JOINUS</a>\n");
      out.write("  </nav>\n");
      out.write("</header>\n");
      out.write("<article>\n");
      out.write("\t<div class=\"title\"><h2>Join Member</h2></div>\n");
      out.write("\t<div class=join>\n");
      out.write("\t<form name=\"join\" action=\"signUp\" method=\"post\" onSubmit=\"regi();return false\">\n");
      out.write("\t\t<table class=\"first\">\n");
      out.write("\t\t\t<tbody>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">아이디</td><td class=\"t\"><input type=text name=\"id\" maxlength=16><span class=\"max\">(최대 16자)</span></td></tr>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">패스워드</td><td class=\"t\"><input type=password name=\"password\" maxlength=16><span class=\"max\">(최대 16자)</span></td></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"tag\">학과</td>\n");
      out.write("\t\t\t\t\t<td class=\"t\">\n");
      out.write("\t\t\t\t\t\t<select name=\"major\" size=\"1\">\n");
      out.write("\t\t\t\t\t\t\t<option value=\"경영학부\">경영학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"국제학부\">국제학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"동아시아언어문화학부\">동아시아언어문화학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"미디어기술콘텐츠학과\">미디어기술콘텐츠학과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"법정경학부\">법정경학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"사회과학부\">사회과학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"생명환경학부\">생명환경학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"생활과학부\">생활과학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"영어영문학부\">영어영문학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"음악과\">음악과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"인문학부\">인문학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"자연과학부\">자연과학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"정보통신전자공학부\">정보통신전자공학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"종교학과\">종교학과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"컴퓨터정보공학부\">컴퓨터정보공학부</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"특스교육과\">특수교육과</option>\n");
      out.write("\t\t\t\t\t\t\t<option value=\"프랑스어문화학과\">프랑스어문화학과</option>\n");
      out.write("\t\t\t\t\t\t</select>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">나이</td><td class=\"t\"><input type=text name=\"age\" maxlength=2><span class=\"max\">살</span></td></tr>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">핸드폰 번호</td><td class=\"t\"><input type=text name=\"phone\" maxlength=13 placeholder=\"010-xxxx-xxxx-\"><span class=\"max\">('-'를 포함해 입력해주세요)</span></td></tr>\n");
      out.write("\t\t\t\t<tr><td class=\"tag\">자기소개</td><td class=\"t\"><textarea cols=40 rows=10 name=pr></textarea></td></tr>\n");
      out.write("\t\t\t\t<tr><td colspan='2'><span class=\"maxt\">(다른사용자들이 열람할 수 있는 글입니다. 신중하게 작성해주세요.)</span></td></tr>\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<br><br>\n");
      out.write("\t\t<table class=\"second\">\n");
      out.write("\t\t\t<tbody>\n");
      out.write("\t\t\t\t<tr><td class=\"t_text\"><div>프로필 사진을 선택하세요</div></td></tr>\n");
      out.write("\t\t\t\t<tr>\n");
      out.write("\t\t\t\t\t<td class=\"t_pic\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man1.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man1\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man2.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man2\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man3.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man3\"><br>\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man4.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man4\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man5.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man5\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man6.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man6\"><br>\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man7.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man7\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man8.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man8\">\n");
      out.write("\t\t\t\t\t\t<img src=\"img/icon/man9.jpg\" width=\"130\" height=\"130\">\n");
      out.write("\t\t\t\t\t\t<input type=\"radio\" name=\"photo\" value=\"man9\"><br>\n");
      out.write("\t\t\t\t\t</td>\n");
      out.write("\t\t\t\t</tr>\n");
      out.write("\t\t\t</tbody>\n");
      out.write("\t\t</table>\n");
      out.write("\t\t<br><br><br>\n");
      out.write("\t\t<input type=\"submit\" value=\"회원가입\">\t\n");
      out.write("\t\t</form>\t\t\n");
      out.write("\t</div>\n");
      out.write("\t\t<div class=\"et\"></div>\t\n");
      out.write("</article>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
